name: Ejecutar Pruebas

on:
  push:
    branches: [ main ] #  Ejecutar solo en la rama main (o la que uses)
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # O la versión de Python que uses
    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt  # <-- Asegúrate de tener un requirements.txt
    - name: Ejecutar pruebas
      run: |
        python -m unittest discover -s tests -p test_*.py #  Ajusta la ruta si es necesario.
